### ISSUE TITLE
Display flickering

### ISSUE THREAD

**Issue by drakemj** [formerlybased/feather-engine#37]
Sometimes the screen will just flicker constantly upon startup. Not sure how to consistently make it occur yet, but on my machine it displays black/white lines flickering across the screen horizontally, usually near the upper thirds of the screen.

**Comment by Adamek-K** [comment]
Hi, I have two machines, both running different operating systems (windows and linux) and both with very different hardware and I have not experienced this problem. Tell me if you experience this issue further, and also please give me some information on your machine (hardware, OS, etc.)

**Comment by drakemj** [comment]
I have two different windows machines, one of which compiles using g++ and one which compiles using cl, the latter being the one that has the occasional flickering. Maybe it has something to do with that...? My desktop is the one with the flickering, it has a AMD Ryzen processor and a AMD Radeon 5700 graphics card (I've had MANY issues with the card before, so maybe it even has something to do with the drivers or something like that)

**Comment by Adamek-K** [comment]
I've used different compilers and haven't had any issues. If you have had issues with the GPU before, I reckon that's the problem. Maybe try updating your graphics drivers?

**Comment by formerlybased** [comment]
Hardware seems to be the problem. Closing issue.
