### ISSUE TITLE
Collision system rework

### ISSUE THREAD

**Issue by drakemj** [formerlybased/feather-engine#41]
Add some hitboxes to RigidEntity, as well as a debug mode which will show the hitboxes

**Comment by Adamek-K** [comment]
I think the entire collision system needs improvements. I will add hitboxes to both regular entities and rigid entities

**Comment by drakemj** [comment]
I've put in a pr, but there are no hitboxes for Entity.

**Comment by Adamek-K** [comment]
I've taken a look at the PR, I still want to do some more review before I merge it

**Comment by Adamek-K** [comment]
Improved with #42 . Leaving open in case more improvements are to be made

**Comment by formerlybased** [comment]
#52 is in reference to this.
