### ISSUE TITLE
Building in Linux is giving me some problems

### ISSUE THREAD

**Issue by drakemj** [formerlybased/feather-engine#48]
When running `scons`, it seems not to be linking the libraries correctly:
![image](https://user-images.githubusercontent.com/62521534/196343951-c391981e-3979-4db5-8aa2-6a37a16586ca.png)

So at first I thought this was because there is no build/lib directory as indicated by the -L flag in the compiler, so I tried to change the directory in main.scons in `LIBPATH`, and I get the same thing:
![image](https://user-images.githubusercontent.com/62521534/196344186-70260134-1037-49f3-9a15-de0b458ab29a.png)

I tried adding wildcard matching to `LIBPATH` (`Glob("../Unix/*"`), in which case these errors do not come up, instead all library functions in all feather/*.cpp files become undefined references.

Not sure if I'm just missing something simple here? Trying to dig through library linking rn because I'm not too terribly familiar.

**Comment by Adamek-K** [comment]
Hi, the project builds fine on my laptop running Linux Mint 20.3 kernel version 5.4 generic. I know that @BoogeyMan24 has had a similar problem on his OSX machine, he might be able to help

**Comment by drakemj** [comment]
So out of curiosity, I installed SDL2 on my system. After doing this, the linker can find SDL2.a, but not the others!
![image](https://user-images.githubusercontent.com/62521534/199408916-c02f53e6-5fa0-420e-8bbc-95ae94954a90.png)
Checking the paths that the linker searches through, I got this:
![image](https://user-images.githubusercontent.com/62521534/199409113-b56ff840-58a8-4839-9bce-e1feb96bf3bf.png)
And sure enough, I found the static library at usr/local/lib:
![image](https://user-images.githubusercontent.com/62521534/199409158-b2e62d49-953e-4af1-81da-38ce4726add1.png)

Which is interesting. Do you have these libraries anywhere else in your ld search paths, maybe? Maybe there is something else I'm missing, but I thought by specifying -L at the library path and -l to specify the .a files everything should work out, but...

**Comment by formerlybased** [comment]
Buildsystem changed. Closing issue
