### ISSUE TITLE
Port to cmake?

### ISSUE THREAD

**Issue by drakemj** [formerlybased/feather-engine#49]
I've heard that cmake is faster and overall more robust compared to scons. Maybe port on over to that? I've created a semi-incomplete sample that I'll send in as a PR and maybe see if that compiles fine (I am still having issues with the libraries, so just wondering if this would work.) Not sure how windows compatibility would work with this

**Comment by Adamek-K** [comment]
I mainly chose SCons because I was more familiar with it. I think porting to CMake could be a good idea.

**Comment by formerlybased** [comment]
@drakemj merged in #50
